Dev database tasks
unilecs/UniLecsBot pull request #9
Opened 2018-11-28 20:28 UTC by futorio

### Примеры использования методов класса TasksDatabase
**Подключение базы данных задач**
```
from tasksdb import TasksDatabase
from task import Task

# Если базы данных не существует произойдёт исключение OSError("database does not exist")
tasks_db = TasksDatabase("bot/dbs/tasks")
```
Для сохранения изменений базу данных необходимо закрыть методом close
```
# Закрыть базу данных с сохранением изменений
tasks_db.close()

# Так же можно вызвать метод, явно указав параметр save=True
tasks_db.close(save=True)

# Для того, чтобы отменить изменения, нужно вызвать метод с параметром save=False
tasks_db.close(save=False)
```
**Поиск в базе данных**

По имени:
```
# Метод вернёт все объекты класса Task, в имени которых есть подстрока "Найти"
tasks = tasks_db.find_tasks_by_name("Найти")
```
По номеру:
```
# Метод вернёт объект класса Task.
# Если такого номера нет, происходит исключение ValueError("task number out of range")
task = tasks_db.find_task_by_number(10)
```
По тегам:
```
# Теги можно передавать в двух режимах. За выбор режима отвечает параметр mode
# mode="or" - хотя бы один тег должен присутвовать в тегах задания
# mode="and" - все теги должны присутствовать в тегах задания
# по умолчанию mode="or"

tags = ["char", "string"]
tasks = tasks_db.find_tasks_by_tags(tags)
tasks = tasks_db.find_tasks_by_tags(tags, mode="and")
```
По уровню сложности:
```
# Метод оперирует классом Complexity и возвращает все задания с данным уровнем сложности
tasks = tasks_db.find_tasks_by_level(Complexity.Easy)
```
**Добавление новых задач**
```
# Метод записывает новый объек класса Task в базу данных
tasks_db.add_task(task)
```
**Редактирование существующих задач**
```
# Редактирование производится по номеру задания
# Параметры редактирования задаются словарём
# Ключ словаря - название столбца

task_number = 10
# Здесь теги передаются в виде строки, а не в виде списка, я перепишу в скором времени
task_params = {"tags": "char|string|chars"}
tasks_db.edit_task(task_number, task_params)
```
### **UPD**
Добавлен атрибут объекта last_task_number. Он создаётся при инициализации нового объекта класса и хранит номер последней задачи. Пример использования - получение рандомной задачи:
```
def get_random_task() -> Task:
	random_number = randomint(1, tasks_db.last_task_number)
	return tasks_db.find_by_number(random_number)
```

2018-11-29 10:41 UTC, LostInKadath requested changes

2018-11-29 10:41 UTC, LostInKadath commented on bot/tasksdb.py
> +                                             ('%'+name+'%',)
Я бы сделал регистронезависимым этот метод. Очень обидно, когда ты задаешь в запросе "вектор" и получаешь пустой ответ, ибо в оригинале "Вектор".

2018-11-29 10:41 UTC, LostInKadath commented on bot/tasksdb.py
> +    def find_tasks_by_tags(self, tags: list, mode: str = "or") -> list:
Кто будет устанавливать `mode`? И кто будет обрабатывать исключения? Если пользователь, то ему это не нужно. Он должен вводить несколько тегов в окошко и получать результат. Значит, должен быть код-обертка над `find_tasks_by_tags`, который принимает от пользователя строку, парсит ее на теги, упаковывает их в список, устанавливает `mode` и вызывает метод `TasksDatabase.find_tasks_by_tags`. Этот код реализован?

2018-11-29 10:41 UTC, LostInKadath commented on bot/tasksdb.py
> +    def find_tasks_by_tags(self, tags: list, mode: str = "or") -> list:
Предлагаю сделать поиск только по `mode=='or'` и выдавать вариант с наибольшим количеством совпадений тегов. Если пользователь ввел один тег, то искать его наличие. Если несколько, то подбирать несколько записей - здесь совпали все теги, здесь не найден один, здесь не найдены два - и из этих записей выбирать ответ пользователю.

Плюс сейчас, насколько я понимаю, никак не распознается ошибка по тегам - типа "такого тега не существует" или "не найдено задач". Кто будет выполнять такую проверку?

2018-11-29 10:41 UTC, LostInKadath commented on bot/tasksdb.py
> +            raise ValueError(f"task №{task.number} exist in the database")
А у нас требования по уникальности ключа только к номеру задачи предоставляются? Разрешается ли ситуация, когда имена задач совпадают?

2018-11-29 10:41 UTC, LostInKadath commented on bot/tasksdb.py
> +                                    "solution_link", "level", "tags"]
Это, наверное, лучше хранить в классе Task и вытягивать из него при необходимости.

2018-11-29 11:03 UTC, futorio commented on bot/tasksdb.py
> +            raise ValueError(f"task №{task.number} exist in the database")
Я добавлю условие уникальности по имени

2018-11-29 11:14 UTC, LostInKadath commented on bot/tasksdb.py
> +            raise ValueError(f"task №{task.number} exist in the database")
Надо? Я в БД не сильно разбираюсь, просто такой вопрос возник, как это разрешается.

2018-11-29 11:14 UTC, LostInKadath commented on bot/tasksdb.py
> +                                             ('%'+name+'%',)
Возможно, эту задачу лучше возложить на вызывающий код бота.

2018-11-29 11:19 UTC, futorio commented on bot/tasksdb.py
> +            raise ValueError(f"task №{task.number} exist in the database")
База данных будет работать, просто это не логично, чтобы существовали разные задачи с одинаковыми названиями

2018-11-29 13:42 UTC, Abdujabbor commented on bot/tasksdb.py
> +    def get_tasks(sql_response: list) -> list:
может здесь заменить наименование как `all` так как у нас и так извелекаем данные от TasksDatabase класса

2018-11-29 13:43 UTC, Abdujabbor commented on bot/tasksdb.py
> +    def find_tasks_by_name(self, name: str) -> list:
`find_by_name` -> если в текущем классе ничего не ищется кроме тасков

2018-11-29 13:44 UTC, Abdujabbor commented on bot/tasksdb.py
> +    def find_task_by_number(self, number: int) -> Task:
`find_by_number`

2018-12-01 17:55 UTC, futorio commented on bot/tasksdb.py
> +            raise ValueError(f"task №{task.number} exist in the database")
Добавлена проверка на оригинальность имени

2018-12-01 17:58 UTC, futorio commented on bot/tasksdb.py
> +                                    "solution_link", "level", "tags"]
В Task для этого создал переменную класса attributes_name

2018-12-01 17:59 UTC, futorio commented on bot/tasksdb.py
> +    def find_tasks_by_name(self, name: str) -> list:
Переназвал

2018-12-01 17:59 UTC, futorio commented on bot/tasksdb.py
> +    def find_task_by_number(self, number: int) -> Task:
Переназвал

2018-12-02 01:58 UTC, unilecs approved these changes

2018-12-02 02:01 UTC, Davletov reviewed
@futorio, сделай изменения, про ктр написал @LostInKadath 
Остальное выглядит отлично!

2018-12-02 10:49 UTC, LostInKadath requested changes

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +    def get_tasks(sql_response: list) -> list:
А я, кстати, не понял, для чего этот метод нужен.

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +        if not name_exist:
Переменная `name_exist` означает, что добавляемое имя уже есть в базе. Тогда исключение должно бросаться при условии `if name_exist`, нет?

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +        if not name_exist:
Это же метод добавления новой задачи в базу?

2018-12-02 10:49 UTC, LostInKadath commented on bot/bot.py
> -        return next((x for x in tasks if x.number == number), None)
pycodestyle ругался? Или просто верстка поехала?

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +    def get_tasks(sql_response: list) -> list:
Если я правильно понял, то БД возвращает некий response, который в этом методе переводится в список объектов Task. Я бы тогда переписал докстринг. Сейчас докстринг просто повторяет код самого метода. Предлагаю:
```Converts list of database response objects to list of Tasks```

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +            raise ValueError("task number out of range")
Наверное, осмысленнее будет выдавать ошибку ```"Database contains no task with number " + number```. Не очень понятно, о каком range идет речь.

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +        sql_params = tuple(['%' + param + '%' for param in tags])
Для общности можно использовать ```param.lower()``` и хранить теги только в нижнем регистре.

2018-12-02 10:49 UTC, LostInKadath commented on bot/tasksdb.py
> +        if not name_exist:
И включу grammar-nazi - в тексте ошибки должно быть existS. =)

2018-12-02 11:05 UTC, futorio commented on bot/tasksdb.py
> +            raise ValueError("task number out of range")
Согласен, поменял на предложенный вариант

2018-12-02 11:18 UTC, LostInKadath commented
![](https://github.trello.services/images/mini-trello-icon.png) [Database: DB development](https://trello.com/c/Yz5aXWnJ/3-database-db-development)

2018-12-02 11:56 UTC, futorio commented on bot/tasksdb.py
> +        sql_params = tuple(['%' + param + '%' for param in tags])
Добавлено. Так же добавлено форматирование тегов в нижний регистр при добавлении задачи

2018-12-02 12:02 UTC, futorio commented on bot/tasksdb.py
> +        if not name_exist:
Исправил

2018-12-02 12:05 UTC, LostInKadath approved these changes

2019-01-16 08:03 UTC, LostInKadath commented
По коду последних пяти коммитов вопросов нет. Однако придержим эту ветку разработки до тех пор, пока не появится кристальная ясность - как дальше жить. =)

2019-01-16 08:03 UTC, closed without merging